version: '3'
services:
  app:
    depends_on:
      - db
    build:
      context: .
    volumes:
      - .:/app
      - dummy_volume:/app/.venv
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true  # 環境によってホットリロードのために必要

  db:
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_DB=develop
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
  dummy_volume: